# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0006_auto_20180417_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Will not be shown to contestants.', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPoolQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooledquizzes.QuizPool')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion')),
            ],
        ),
    ]

